# Generated by Django 4.2.6 on 2023-11-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('author_name', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('pages', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
